### ISSUE TITLE
index.html links are absolute (2.3)

### ISSUE THREAD

**Issue by vladdu** [kiliman/tailwindui-crawler#10]
This makes it hard to just browse the files, a server is needed...

**Comment by kiliman** [comment]
That's why I recommend using the `serve` package.

```bash
yarn add -g serve
serve
```

Run `serve` from the root of your OUTPUT folder (where index.html is located).

![image](https://user-images.githubusercontent.com/47168/79492996-d6264e00-7fee-11ea-89a8-c7ca3ef83162.png)

![image](https://user-images.githubusercontent.com/47168/79493079-f35b1c80-7fee-11ea-82aa-47fc474e2727.png)

![image](https://user-images.githubusercontent.com/47168/79493122-01a93880-7fef-11ea-92ee-bf1643f9f0c1.png)

**Comment by vladdu** [comment]
I saw that afterwards, but it still doesn't work. I needed to use "yarn global add serve" and manually add ~/.yarn/bin to $PATH. After that, the components are shown completely unstyled.

![Annotation 2020-04-16 212123](https://user-images.githubusercontent.com/9707/79497875-bad83480-8028-11ea-832d-cbfedaf30b14.png)

I realize that using relative links makes things a bit more complicated and probably not worth it, because it's more than removing the initial /

**Comment by vladdu** [comment]
Hmm, ok, so I needed addTailwindCss: it isn't clear what that option does: add a link where? I thought initially it's only a link to their site.

**Comment by kiliman** [comment]
Sorry, the `addTailwindCss` transformer adds the following to each component HTML file. If you want to use the Inter font (the same as on the tailwindui.com site), add the `userInter` transformer.

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tailwindcss/ui@latest/dist/tailwind-ui.min.css" />
```

**Comment by kiliman** [comment]
Also, you may want to upgrade to v2.3. The component code no longer includes the Alpine.js markup, so it won't be interactive on your local copy. The update adds an option to ensure that it gets the the version with Alpine.

**Comment by vladdu** [comment]
Thanks. I created a PR to make it clear how to have styled components when served via serve
