### ISSUE TITLE
New Version 3 ideas

### ISSUE THREAD

**Issue by kiliman** [kiliman/tailwindui-crawler#28]
Just posting this here to put down my thoughts on what the next version of the crawler will be. Calling this v3, since it will have some breaking changes.

* Always store the original interactive (alpine JS) versions and HTML comment version regardless of transformers. This is to ensure that we can still display the component properly locally (offline). Also, Adam adds additional markup around the component to make it look better in the preview. This markup is not present in the HTML comments version, so it will not look correct in that mode. Transformers will store their output independent of these original versions.
* Ability to apply transformers from offline viewer. That is, the user can apply the changeColor transformer while viewing the component in Preview mode. This will apply the transformer on the cached alpine version.
* Update config to use JSON format. Still keep .env for credentials, but the rest should be in a more readable and extensible format.
* Add a configurable workflow that can script out tasks, like generating the tailwind CSS from the config. Generating a list of class names for use by the prefixClasses transformer, etc.
* Finish up transformers for adding transition support for Vue and React. Make it extensible enough that it would be relatively easy to customize for Angular and other frameworks.

If anyone has any comments, please feel free to post.

**Comment by kiliman** [comment]
* Add support for tracking changes of components. Show which components were changed by viewing the git logs (add support to auto-commit diffs after crawling).
* Add support to notify user when a custom (derived) component changes in Tailwind UI. That is, let's say you are using the Notification component from Tailwind UI, and create a React version. The crawler should tell you whenever that component changes in the original so you can apply those changes to your custom component.<br><br>The way I do that now is that I put the file path and commit hash (the version which I copied) of the original component in a comment in my React component. Then I have a script that will tell me if any of the components my React components derived from have changed. I then apply those changes to my version, and update the commit hash. Rinse and repeat.

**Comment by connecteev** [comment]
@kiliman these are all 🔥. Thanks for your work with this repo - I am especially excited about these features below and can't wait to use this.

- Finish up transformers for adding transition support for Vue and React (esp Vue in my case)
- Always store the original interactive (alpine JS) versions and HTML comment version regardless of transformers
- Add support for tracking changes of components
- Notify user when a custom (derived) component changes in Tailwind UI
- #16 

I haven't thought this through and I'm not sure if there's a way to integrate https://github.com/GregBrimble/tailwindui-crawler-action into your repo here, so that the crawler auto-runs / builds based on the github action settings. It would be great to have it all live in one place and respects your tailwindui-crawler config.

Once again thanks..

**Comment by kiliman** [comment]
@vesper8 I noticed you posted an issue on https://tailwind.run repo about providing source... well since they haven't done it yet, I'm working on a new project: https://twfiddle.app

https://github.com/kiliman/twfiddle

The main thing I want to implement is the ability to save files linked to your profile. I will most likely use GitHub gists, so we get versioning as well.

Anyway, feel free to post your wish list as issues on that repo.
